stages:
  - deploy

variables:
  DEPLOY_DIR: "/home/ubuntu/deployed/hive-attention-tokens/"


deploy:
  stage: deploy
  script:
    - pwd
    - whoami
    - rm -rf $DEPLOY_DIR
    - mkdir -p $DEPLOY_DIR
    - cp -r * $DEPLOY_DIR
    - cd $DEPLOY_DIR
    - pwd
    - sudo pip3 install .
    - sudo pkill -f hive_attention_tokens || true
    - sudo mkdir -p /var/log/hive-attention-tokens/
    - sudo nohup hive_attention_tokens >> /var/log/hive-attention-tokens/hat.log 2>&1&
  only:
    - dev
  tags:
    - testnet