stages:
  - deploy

variables:
  DEPLOY_DIR: "/home/ubuntu/deployed/hive-attention-tokens/"


deploy:
  stage: deploy
  script:
    - pwd
    - whoami
    - rm -rf $DEPLOY_DIR
    - mkdir -p $DEPLOY_DIR
    - cp -r * $DEPLOY_DIR
    - cd $DEPLOY_DIR
    - pwd
    - sudo pip3 install .
    - pkill -f hive_attention_tokens || true
    - sudo hive_attention_tokens
  only:
    - dev
  tags:
    - testnet